name: Check for new pnpm release

on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  check-tags:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}
        fetch-depth: 0
    - name: Check for new tags
      run: |
        ./.github/scripts/new_release_check_pnpm.sh
